# Generated by Django 5.2.4 on 2025-09-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatmessage'),
        ('guests', '0014_alter_followupreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='guest_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='guests.guestentry'),
        ),
    ]
