# Generated by Django 5.2.4 on 2025-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_chatmessage_guest_card'),
        ('guests', '0015_guestentry_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code like #FF7A59', max_length=7, null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='accounts_ch_created_974fb1_idx'),
        ),
    ]
