# Generated by Django 5.2.4 on 2025-09-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chatmessage_deleted_chatmessage_edited_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='accounts_ch_created_974fb1_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='color',
        ),
    ]
