# Generated by Django 5.2.4 on 2025-09-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_chatmessage_accounts_ch_created_974fb1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
    ]
