# Generated by Django 5.2.4 on 2025-09-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chatmessage_deleted_chatmessage_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited_at',
        ),
    ]
