# Generated by Django 5.2.4 on 2025-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_chatmessage_deleted_remove_chatmessage_edited_and_more'),
        ('guests', '0015_guestentry_age_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='accounts_ch_created_974fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='accounts_ch_sender__dce0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['guest_card', 'created_at'], name='accounts_ch_guest_c_8fe9d6_idx'),
        ),
    ]
