# Generated by Django 5.2.4 on 2025-09-30 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pinned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
