# Generated by Django 5.2.4 on 2025-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_chatmessage_pinned_at_chatmessage_pinned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='link_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='link_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
