# Generated by Django 5.2.4 on 2025-10-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_chatmessage_attachment_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
