# Generated by Django 5.2.4 on 2025-10-14 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_chatmessage_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('service', 'Sunday Service'), ('midweek', 'Midweek Recharge'), ('btf', 'Breakthrough Festival'), ('code red', 'Code Red Revival'), ('followup', 'Guest Follow-up'), ('meeting', 'Team Meeting'), ('sos', 'SOS'), ('conclave', 'Conclave'), ('other', 'Other')], max_length=50)),
                ('day_of_week', models.CharField(blank=True, choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['day_of_week', 'time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='accounts.event')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'event', 'date')},
            },
        ),
    ]
