# Generated by Django 5.2.4 on 2025-10-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_seed_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days this event lasts'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
