# Generated by Django 5.2.4 on 2025-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_cleanup_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
