# Generated by Django 5.2.4 on 2025-10-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_chatmessage_link_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='link_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
