# Generated by Django 5.2.4 on 2025-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('service', 'Service'), ('midweek', 'Midweek'), ('followup', 'Guest Follow-up'), ('meeting', 'Team Meeting'), ('training', 'Training'), ('other', 'Other')], max_length=50),
        ),
    ]
