# Generated by Django 5.2.4 on 2025-10-16 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_mode',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Service', 'Service'), ('Followup', 'Guest Follow-up'), ('Meeting', 'Meeting'), ('Training', 'Training'), ('Other', 'Other')], max_length=50),
        ),
    ]
