# Generated by Django 5.2.4 on 2025-10-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_event_attendance_mode_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring_weekly',
            field=models.BooleanField(default=False),
        ),
    ]
