# Generated by Django 5.2.4 on 2025-08-16 21:18

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('custom_id', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('title', models.CharField(blank=True, choices=[('Chief', 'Chief'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Pastor', 'Pastor'), ('Prof.', 'Prof.')], default='Mr.', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Not Stated', 'Not Stated')], default='Single', max_length=20)),
                ('home_address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('date_of_visit', models.DateField(default=django.utils.timezone.localdate)),
                ('purpose_of_visit', models.CharField(blank=True, choices=[('Home Church', 'Home Church'), ('Occasional Visit', 'Occasional Visit'), ('One-Time Visit', 'One-Time Visit'), ('Special Programme Visit', 'Special Programme Visit'), ('Not Stated', 'Not Stated')], default='Home Church', max_length=30)),
                ('channel_of_visit', models.CharField(blank=True, choices=[('Billboard (Grammar School)', 'Billboard (Grammar School)'), ('Billboard (Kosoko)', 'Billboard (Kosoko)'), ('Billboard (Ojodu)', 'Billboard (Ojodu)'), ('Facebook', 'Facebook'), ('Flyer', 'Flyer'), ('Instagram', 'Instagram'), ('Referral', 'Referral'), ('Self', 'Self'), ('Visit', 'Visit'), ('YouTube', 'YouTube'), ('Not Stated', 'Not Stated')], default='Referral', max_length=30)),
                ('service_attended', models.CharField(blank=True, choices=[('Black Ball', 'Black Ball'), ('Breakthrough Campaign', 'Breakthrough Campaign'), ('Breakthrough Festival', 'Breakthrough Festival'), ('Code Red. Revival', 'Code Red. Revival'), ('Cross Over', 'Cross Over'), ('Deep Dive', 'Deep Dive'), ('Family Hangout', 'Family Hangout'), ('Forecasting', 'Forecasting'), ('Life Masterclass', 'Life Masterclass'), ('Love Lounge', 'Love Lounge'), ('Midweek Recharge', 'Midweek Recharge'), ('Midyear Praise Party', 'Midyear Praise Party'), ('Outreach', 'Outreach'), ('Praise Party', 'Praise Party'), ('Quantum Leap', 'Quantum Leap'), ('Recalibrate Marathon', 'Recalibrate Marathon'), ('Singles Connect', 'Singles Connect'), ('Supernatural Encounter', 'Supernatural Encounter')], default='Love Lounge', max_length=50)),
                ('referrer_name', models.CharField(blank=True, max_length=100)),
                ('referrer_phone_number', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Select Status', 'Select Status'), ('Planted', 'Planted'), ('Planted Elsewhere', 'Planted Elsewhere'), ('Relocated', 'Relocated'), ('Work in Progress', 'Work in Progress')], default='Select Status', max_length=30)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_guests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'Tiktok')], max_length=20)),
                ('handle', models.CharField(max_length=255)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='guests.guestentry')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('note', models.TextField()),
                ('service_sunday', models.BooleanField(default=False)),
                ('service_midweek', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guests.guestentry')),
            ],
            options={
                'ordering': ['-report_date'],
                'unique_together': {('guest', 'report_date')},
            },
        ),
    ]
