# Generated by Django 5.2.4 on 2025-07-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='channel_of_visit',
            field=models.CharField(blank=True, choices=[('Billboard (Grammar School)', 'Billboard (Grammar School)'), ('Billboard (Kosoko)', 'Billboard (Kosoko)'), ('Billboard (Ojodu)', 'Billboard (Ojodu)'), ('Facebook', 'Facebook'), ('Flyer', 'Flyer'), ('Instagram', 'Instagram'), ('Referral', 'Referral'), ('Self', 'Self'), ('Visit', 'Visit'), ('YouTube', 'YouTube'), ('Not Stated', 'Not Stated')], max_length=30),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='followup_status',
            field=models.CharField(choices=[('Select Status', 'Select Status'), ('Planted', 'Planted'), ('Planted Elsewhere', 'Planted Elsewhere'), ('Relocated', 'Relocated'), ('Work in Progress', 'Work in Progress')], default='Select Status', max_length=20),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Mr.', max_length=10),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Not Stated', 'Not Stated')], max_length=10),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='purpose_of_visit',
            field=models.CharField(blank=True, choices=[('Home Church', 'Home Church'), ('Ocaassional Visit', 'Occasional Visit'), ('One-Time Visit', 'One-Time Visit'), ('Special Programme Visit', 'Special Programme Visit'), ('Not Stated', 'Not Stated')], max_length=30),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='referrer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='referrer_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='service_attended',
            field=models.CharField(blank=True, choices=[('Black Ball', 'Black Ball'), ('Breakthrough Campaign', 'Breakthrough Campaign'), ('Breakthrough Festival', 'Breakthrough Festival'), ('Code Red. Revival', 'Code Red. Revival'), ('Cross Over', 'Cross Over'), ('Deep Dive', 'Deep Dive'), ('Family Hangout', 'Family Hangout'), ('Forecasting', 'Forecasting'), ('Life Masterclass', 'Life Masterclass'), ('Love Lounge', 'Love Lounge'), ('Midweek Recharge', 'Midweek Recharge'), ('Outreach', 'Outreach'), ('Quantun Leap', 'Quantum Leap'), ('Recalibrate Marathon', 'Recalibrate Marathon'), ('Singles Connect', 'Singles Connect'), ('Supernatural Encounter', 'Supernatural Encounter')], max_length=30),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='title',
            field=models.CharField(blank=True, choices=[('Chief', 'Chief'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Pastor', 'Pastor'), ('Prof.', 'Prof.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
