# Generated by Django 5.2.4 on 2025-07-18 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guestentry_channel_of_visit_guestentry_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestentry',
            old_name='followup_status',
            new_name='status',
        ),
    ]
