# Generated by Django 5.2.4 on 2025-08-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_guestentry_channel_of_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestentry',
            name='created_by',
        ),
    ]
