# Generated by Django 5.2.4 on 2025-07-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_rename_followup_status_guestentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='picture',
            field=models.ImageField(blank=True, default='default_guest.jpg', null=True, upload_to='guest_pictures/'),
        ),
    ]
