# Generated by Django 5.2.4 on 2025-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guestentry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Not Stated', 'Not Stated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='purpose_of_visit',
            field=models.CharField(blank=True, choices=[('Home Church', 'Home Church'), ('Occasional Visit', 'Occasional Visit'), ('One-Time Visit', 'One-Time Visit'), ('Special Programme Visit', 'Special Programme Visit'), ('Not Stated', 'Not Stated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='service_attended',
            field=models.CharField(blank=True, choices=[('Black Ball', 'Black Ball'), ('Breakthrough Campaign', 'Breakthrough Campaign'), ('Breakthrough Festival', 'Breakthrough Festival'), ('Code Red. Revival', 'Code Red. Revival'), ('Cross Over', 'Cross Over'), ('Deep Dive', 'Deep Dive'), ('Family Hangout', 'Family Hangout'), ('Forecasting', 'Forecasting'), ('Life Masterclass', 'Life Masterclass'), ('Love Lounge', 'Love Lounge'), ('Midweek Recharge', 'Midweek Recharge'), ('Outreach', 'Outreach'), ('Quantum Leap', 'Quantum Leap'), ('Recalibrate Marathon', 'Recalibrate Marathon'), ('Singles Connect', 'Singles Connect'), ('Supernatural Encounter', 'Supernatural Encounter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='status',
            field=models.CharField(choices=[('Select Status', 'Select Status'), ('Planted', 'Planted'), ('Planted Elsewhere', 'Planted Elsewhere'), ('Relocated', 'Relocated'), ('Work in Progress', 'Work in Progress')], default='Select Status', max_length=30),
        ),
    ]
