# Generated by Django 5.2.4 on 2025-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guestentry_date_of_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20),
        ),
    ]
