# Generated by Django 5.2.4 on 2025-07-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_alter_guestentry_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='picture',
            field=models.ImageField(blank=True, default='guest_pictures/default_guest.jpg', null=True, upload_to='guest_pictures/'),
        ),
    ]
