# Generated by Django 5.2.4 on 2025-07-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_alter_guestentry_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('outcome', models.CharField(choices=[('Reached', 'Reached'), ('Pending', 'Pending'), ('Not Available', 'Not Available'), ('Disengaged', 'Disengaged')], max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='guests.guestentry')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
    ]
