# Generated by Django 5.2.4 on 2025-07-20 21:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0007_followupreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followupreport',
            unique_together={('guest', 'report_date')},
        ),
        migrations.AddField(
            model_name='followupreport',
            name='attended_midweek',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='attended_sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reports', to='guests.guestentry'),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='report_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='followupreport',
            name='outcome',
        ),
    ]
