# Generated by Django 5.2.4 on 2025-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0008_remove_followupreport_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20),
        ),
    ]
