# Generated by Django 5.2.4 on 2025-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0009_alter_guestentry_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
