# Generated by Django 5.2.4 on 2025-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0010_alter_guestentry_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
