# Generated by Django 5.2.4 on 2025-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_guestentry_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='assigned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
