# Generated by Django 5.2.4 on 2025-07-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_alter_guestentry_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
