# Generated by Django 5.2.4 on 2025-09-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_alter_guestentry_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='service_others',
            field=models.BooleanField(default=False),
        ),
    ]
