# Generated by Django 5.2.4 on 2025-07-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_alter_guestentry_date_of_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='date_of_birth',
            field=models.CharField(blank=True, null=True),
        ),
    ]
