# Generated by Django 5.2.4 on 2025-09-02 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0013_followupreport_service_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
