# Generated by Django 5.2.4 on 2025-09-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_alter_followupreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='age_range',
            field=models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18–25', '18–25'), ('26–35', '26–35'), ('36–45', '36–45'), ('46 and Above', '46 and Above')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='channel_of_visit',
            field=models.CharField(blank=True, choices=[('Billboard (Grammar School)', 'Billboard (Grammar School)'), ('Billboard (Kosoko)', 'Billboard (Kosoko)'), ('Billboard (Ojodu)', 'Billboard (Ojodu)'), ('Facebook', 'Facebook'), ('Family & Friends', 'Family & Friends'), ('Flyer', 'Flyer'), ('Instagram', 'Instagram'), ('Referral', 'Referral'), ('Self', 'Self'), ('Visit', 'Visit'), ('YouTube', 'YouTube'), ('Others', 'Others')], max_length=30),
        ),
    ]
