# Generated by Django 5.2.4 on 2025-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0014_alter_guestentry_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='picture',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dahx6bbyr/image/upload/v1753468187/default_guest_memhgq.jpg', null=True, upload_to='guest_pictures/'),
        ),
    ]
