# Generated by Django 5.2.4 on 2025-08-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0015_alter_guestentry_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='guest_pictures/'),
        ),
    ]
