# Generated by Django 5.2.4 on 2025-08-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_alter_guestentry_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
