# Generated by Django 5.2.4 on 2025-08-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0017_followupreport_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupreport',
            old_name='notes',
            new_name='note',
        ),
    ]
