# Generated by Django 5.2.4 on 2025-08-07 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0018_rename_notes_followupreport_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupreport',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guests.guestentry'),
        ),
    ]
