# Generated by Django 5.2.4 on 2025-08-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0019_alter_followupreport_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupreport',
            old_name='attended_midweek',
            new_name='service_midweek',
        ),
        migrations.RenameField(
            model_name='followupreport',
            old_name='attended_sunday',
            new_name='service_sunday',
        ),
    ]
