# Generated by Django 5.2.4 on 2025-08-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0020_rename_attended_midweek_followupreport_service_midweek_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupreport',
            name='updated_at',
        ),
    ]
