# Generated by Django 5.2.4 on 2025-08-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0021_remove_followupreport_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
