# Generated by Django 5.2.4 on 2025-08-08 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0022_followupreport_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='channel_of_visit',
            field=models.CharField(blank=True, choices=[('Billboard (Grammar School)', 'Billboard (Grammar School)'), ('Billboard (Kosoko)', 'Billboard (Kosoko)'), ('Billboard (Ojodu)', 'Billboard (Ojodu)'), ('Facebook', 'Facebook'), ('Flyer', 'Flyer'), ('Instagram', 'Instagram'), ('Referral', 'Referral'), ('Self', 'Self'), ('Visit', 'Visit'), ('YouTube', 'YouTube'), ('Not Stated', 'Not Stated')], default='Referral', max_length=30),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Not Stated', 'Not Stated')], default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='purpose_of_visit',
            field=models.CharField(blank=True, choices=[('Home Church', 'Home Church'), ('Occasional Visit', 'Occasional Visit'), ('One-Time Visit', 'One-Time Visit'), ('Special Programme Visit', 'Special Programme Visit'), ('Not Stated', 'Not Stated')], default='Home Church', max_length=30),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='service_attended',
            field=models.CharField(blank=True, choices=[('Black Ball', 'Black Ball'), ('Breakthrough Campaign', 'Breakthrough Campaign'), ('Breakthrough Festival', 'Breakthrough Festival'), ('Code Red. Revival', 'Code Red. Revival'), ('Cross Over', 'Cross Over'), ('Deep Dive', 'Deep Dive'), ('Family Hangout', 'Family Hangout'), ('Forecasting', 'Forecasting'), ('Life Masterclass', 'Life Masterclass'), ('Love Lounge', 'Love Lounge'), ('Midweek Recharge', 'Midweek Recharge'), ('Outreach', 'Outreach'), ('Quantum Leap', 'Quantum Leap'), ('Recalibrate Marathon', 'Recalibrate Marathon'), ('Singles Connect', 'Singles Connect'), ('Supernatural Encounter', 'Supernatural Encounter')], default='Love Lounge', max_length=50),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='title',
            field=models.CharField(blank=True, choices=[('Chief', 'Chief'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Pastor', 'Pastor'), ('Prof.', 'Prof.')], default='Mr.', max_length=20),
        ),
    ]
