# Generated by Django 5.2.4 on 2025-08-10 05:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0023_alter_guestentry_channel_of_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
