# Generated by Django 5.2.4 on 2025-08-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0024_alter_guestentry_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='custom_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='social_media_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='social_media_type',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'WhatsApp'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestentry',
            name='service_attended',
            field=models.CharField(blank=True, choices=[('Black Ball', 'Black Ball'), ('Breakthrough Campaign', 'Breakthrough Campaign'), ('Breakthrough Festival', 'Breakthrough Festival'), ('Code Red. Revival', 'Code Red. Revival'), ('Cross Over', 'Cross Over'), ('Deep Dive', 'Deep Dive'), ('Family Hangout', 'Family Hangout'), ('Forecasting', 'Forecasting'), ('Life Masterclass', 'Life Masterclass'), ('Love Lounge', 'Love Lounge'), ('Midweek Recharge', 'Midweek Recharge'), ('Outreach', 'Outreach'), ('Praise Party', 'Praise Party'), ('Quantum Leap', 'Quantum Leap'), ('Recalibrate Marathon', 'Recalibrate Marathon'), ('Singles Connect', 'Singles Connect'), ('Supernatural Encounter', 'Supernatural Encounter')], default='Love Lounge', max_length=50),
        ),
    ]
