# Generated by Django 5.2.4 on 2025-08-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0025_guestentry_custom_id_guestentry_social_media_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='social_media_type',
            field=models.CharField(blank=True, choices=[('Whatsapp', 'WhatsApp'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('LinkedIn', 'LinkedIn'), ('Tiktok', 'Tiktok')], max_length=20, null=True),
        ),
    ]
