# Generated by Django 5.2.4 on 2025-08-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0026_alter_guestentry_social_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestentry',
            name='social_media_type',
        ),
    ]
