# Generated by Django 5.2.4 on 2025-08-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0027_remove_guestentry_social_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='date_of_visit',
            field=models.DateField(),
        ),
    ]
