# Generated by Django 5.2.4 on 2025-08-12 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0028_alter_guestentry_date_of_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestentry',
            name='date_of_visit',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
