# Generated by Django 5.2.4 on 2025-08-13 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0029_alter_guestentry_date_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestentry',
            name='social_media_handle',
        ),
        migrations.CreateModel(
            name='SocialMediaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'Tiktok')], max_length=20)),
                ('handle', models.CharField(max_length=255)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='guests.guestentry')),
            ],
        ),
    ]
