# Generated by Django 5.2.4 on 2025-08-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0030_remove_guestentry_social_media_handle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
