# Generated by Django 5.2.4 on 2025-08-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0031_guestentry_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestentry',
            name='created_at',
        ),
    ]
