# Generated by Django 5.2.4 on 2025-08-26 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sound', models.CharField(choices=[('chime1', 'Chime 1'), ('chime2', 'Chime 2'), ('chime3', 'Chime 3'), ('chime4', 'Chime 4'), ('chime5', 'Chime 5'), ('chime6', 'Chime 6'), ('chime7', 'Chime 7'), ('chime8', 'Chime 8')], default='chime1', max_length=20)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
